---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-service
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app
...

